sudo: required
services:
    - docker
before_install:
    - docker build -t hardik3296/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true hardik3296/react-test npm test -- --coverage
after-success:
    - docker build -t hardik3296/multi-client ./client
    - docker build -t hardik3296/multi-nginx ./nginx
    - docker build -t hardik3296/multi-server ./server
    - docker build -t hardik3296/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push hardik3296/multi-client
    - docker push hardik3296/multi-nginx
    - docker push hardik3296/multi-server
    - docker push hardik3296/multi-worker
